resources:
  projectroot:

mongo:
    url: "ds047642.mongolab.com:47642"
    db: "heroku_rzn64j7z"
    username: "gtimesapp"
    password: "elieitan123"

admin:
  username: "goodtimesAdmin"
  password: "$2a$10$QX8BFZh69TpV7Gs7xhghsOc5kEC6gjik9uqhTkJyIGE998pLfilHK"
  email: "eli.segal@gmail.com"